# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
